==================== FedAvg ====================                               
Experiment Arguments:                                                          
{
    'method': 'fedavg',
    'dataset': {
        'name': 'svhn',
        'client_num': 100,
        'test_ratio': 0.25,
        'val_ratio': 0.0,
        'seed': 42,
        'split': 'sample',
        'IID_ratio': 0.0,
        'monitor_window_name_suffix': 'svhn-100clients-0%IID-Dir(0.1)-seed42',
        'alpha': 0.1,
        'min_samples_per_client': 10
    },
    'model': {
        'name': 'avgcnn',
        'use_torchvision_pretrained_weights': True,
        'external_model_weights_path': None
    },
    'optimizer': {
        'lr': 0.01,
        'dampening': 0,
        'weight_decay': 0,
        'momentum': 0.7,
        'nesterov': False,
        'name': 'sgd'
    },
    'mode': 'parallel',
    'parallel': {
        'ray_cluster_addr': None,
        'num_cpus': 24.0,
        'num_gpus': 1.0,
        'num_workers': 2
    },
    'common': {
        'seed': 42,
        'join_ratio': 0.1,
        'global_epoch': 400,
        'local_epoch': 5,
        'batch_size': 32,
        'reset_optimizer_on_global_epoch': True,
        'straggler_ratio': 0,
        'straggler_min_local_epoch': 0,
        'buffers': 'global',
        'client_side_evaluation': True,
        'test': {
            'client': {
                'interval': 100,
                'finetune_epoch': 5,
                'train': False,
                'val': False,
                'test': True
            },
            'server': {
                'interval': -1,
                'train': False,
                'val': False,
                'test': True,
                'model_in_train_mode': False
            }
        },
        'verbose_gap': 10,
        'monitor': None,
        'use_cuda': True,
        'save_log': True,
        'save_model': False,
        'save_learning_curve_plot': True,
        'save_metrics': True,
        'delete_useless_run': True
    },
    'fedprox': {
        'mu': 0.01
    },
    'pfedsim': {
        'warmup_round': 0.5
    }
}
Traceback (most recent call last):                                             
  File "D:\new-FL-bench\src\server\fedavg.py", line 915, in run_experiment     
    self.train()                                                               
  File "D:\new-FL-bench\src\server\fedavg.py", line 443, in train              
    self.train_one_round()                                                     
  File "D:\new-FL-bench\src\server\fedavg.py", line 471, in train_one_round    
    client_packages = self.trainer.train()                                     
                      ^^^^^^^^^^^^^^^^^^^^                                     
  File "D:\new-FL-bench\src\utils\trainer.py", line 86, in _parallel_train     
    client_package = ray.get(finished)                                         
                     ^^^^^^^^^^^^^^^^^                                         
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\auto_init
_hook.py", line 21, in auto_init_wrapper                                       
    return fn(*args, **kwargs)                                                 
           ^^^^^^^^^^^^^^^^^^^                                                 
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\client_mo
de_hook.py", line 103, in wrapper                                              
    return func(*args, **kwargs)                                               
           ^^^^^^^^^^^^^^^^^^^^^                                               
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\worker.py
", line 2755, in get                                                           
    values, debugger_breakpoint = worker.get_objects(object_refs,              
timeout=timeout)                                                               
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^                                                                            
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\worker.py
", line 908, in get_objects                                                    
    raise value                                                                
ray.exceptions.RaySystemError: System error:                                   
traceback: Traceback (most recent call last):                                  
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 460, in deserialize_objects                                     
    obj = self._deserialize_object(data, metadata, object_ref)                 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 317, in _deserialize_object                                     
    return self._deserialize_msgpack_data(data, metadata_fields)               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 272, in _deserialize_msgpack_data                               
    python_objects = self._deserialize_pickle5_data(pickle5_data)              
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 262, in _deserialize_pickle5_data                               
    obj = pickle.loads(in_band)                                                
          ^^^^^^^^^^^^^^^^^^^^^                                                
MemoryError                                                                    
                                                                               
                                                                               
Exception occurred: System error:                                              
traceback: Traceback (most recent call last):                                  
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 460, in deserialize_objects                                     
    obj = self._deserialize_object(data, metadata, object_ref)                 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 317, in _deserialize_object                                     
    return self._deserialize_msgpack_data(data, metadata_fields)               
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 272, in _deserialize_msgpack_data                               
    python_objects = self._deserialize_pickle5_data(pickle5_data)              
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^              
  File                                                                         
"C:\Users\20834\anaconda3\envs\FedCPMD\Lib\site-packages\ray\_private\serializa
tion.py", line 262, in _deserialize_pickle5_data                               
    obj = pickle.loads(in_band)                                                
          ^^^^^^^^^^^^^^^^^^^^^                                                
MemoryError                                                                    
                                                                               
